# Generated by Django 3.2.18 on 2023-03-07 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Содержимое пуша')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок пуша')),
                ('url', models.CharField(max_length=255, null=True, verbose_name='Ссылка куда переведет человека при нажатии на пуш')),
                ('status', models.BooleanField(default=False, verbose_name='Статус отправки пуш уведомления')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
        ),
    ]
