version: '2'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
     - 5432:5432
    command: --autovacuum=off --fsync=off --synchronous_commit=off --full_page_writes=off --work_mem=12MB --max-connections=10 --max_wal_senders=0

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: celery -A app worker -l info
    volumes:
      - .:/code/
      - ./media/:/media
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: celery -A app beat -l info -S django
    volumes:
      - ./code/:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - redis
      - celery

  nginx:
    image: nginx:1-alpine
    environment:
      - TZ=Asia/Almaty
    volumes:
      - static:/static